apiVersion: v1
entries:
  airports-api:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-09-12T15:36:46.5746577+03:00"
    description: A Helm chart for Kubernetes
    digest: cfc713b7cb1ba5d518c1daebfc332b5d773be74117a797a1a86dc38400d2ca4a
    name: airports-api
    type: application
    urls:
    - airports-api-0.1.0.tgz
    version: 0.1.0
  airports-consumer:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-09-12T15:36:46.5746577+03:00"
    description: A Helm chart for Kubernetes
    digest: e9f24420f32c4c6805e4c6e3bd6c499b251ecc70b4ed9b9d8122880c86a6bae5
    name: airports-consumer
    type: application
    urls:
    - airports-consumer-0.1.0.tgz
    version: 0.1.0
  airports-frontend:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-09-12T15:36:46.5752031+03:00"
    description: A Helm chart for Kubernetes
    digest: 4e48c355d3a9a12090cba4e2d2593de46f14324153b28ec3a3d163f0fd24e249
    name: airports-frontend
    type: application
    urls:
    - airports-frontend-0.1.0.tgz
    version: 0.1.0
  airports-kafka:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-09-12T15:36:46.5752031+03:00"
    description: A Helm chart for Kubernetes
    digest: a35aebb303931dfbff269ab61ed27d3e13ae837a6ab9d8a7f02fae6ed29eb258
    name: airports-kafka
    type: application
    urls:
    - airports-kafka-0.1.0.tgz
    version: 0.1.0
  airports-postgres:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-09-12T15:36:46.5757719+03:00"
    description: A Helm chart for Kubernetes
    digest: d05fe06e7fa0cb42910208e51d3927bd3742c77947c46f06f5bb04a49e71e966
    name: airports-postgres
    type: application
    urls:
    - airports-postgres-0.1.0.tgz
    version: 0.1.0
  airports-producer:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-09-12T15:36:46.5757719+03:00"
    description: A Helm chart for Kubernetes
    digest: d1439b42efb2dc6b46ae59f51da46d926cb01c36a2cc868fa9bc511e83cffb0e
    name: airports-producer
    type: application
    urls:
    - airports-producer-0.1.0.tgz
    version: 0.1.0
  helm-airports:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-09-12T15:36:46.5741109+03:00"
    dependencies:
    - name: airports-api
      repository: https://daniacobext.github.io/HelmAirportsAPI/charts
      version: 0.1.0
    - name: airports-producer
      repository: https://daniacobext.github.io/HelmAirportsProducer/charts
      version: 0.1.0
    - name: airports-consumer
      repository: https://daniacobext.github.io/HelmAirportsConsumer/charts
      version: 0.1.0
    - name: airports-frontend
      repository: https://daniacobext.github.io/HelmAirportsFrontend/charts
      version: 0.1.0
    - name: airports-kafka
      repository: https://daniacobext.github.io/HelmAirportsKafka/charts
      version: 0.1.0
    - name: airports-postgres
      repository: https://daniacobext.github.io/HelmAirportsPostgres/charts
      version: 0.1.0
    description: A Helm chart for Kubernetes
    digest: 2119d9fc6b2cb0c3bee053962303c3c472062159be3f64d7227e6acc9c3ef97f
    name: helm-airports
    type: application
    urls:
    - helm-airports-0.1.0.tgz
    version: 0.1.0
generated: "2023-09-12T15:36:46.5735658+03:00"
